### ISSUE TITLE
SearchView crash NoSuchFieldException mCursorDrawable

### ISSUE THREAD

**Issue by bignadad** [AllanWang/KAU#176]
Getting this crash 

`
2018-12-17 09:41:27.013 7993-7993/com.memoria.photos.gallery W/System.err: java.lang.NoSuchFieldException: No field mCursorDrawable in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
2018-12-17 09:41:27.015 7993-7993/com.memoria.photos.gallery W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
2018-12-17 09:41:27.015 7993-7993/com.memoria.photos.gallery W/System.err:     at ca.allanwang.kau.utils.ColorUtilsKt.tintCursor(ColorUtils.kt:242)
2018-12-17 09:41:27.015 7993-7993/com.memoria.photos.gallery W/System.err:     at com.memoria.photos.gallery.activities.MediaActivity$onCreateOptionsMenu$2$3.invoke(MediaActivity.kt:320)
2018-12-17 09:41:27.016 7993-7993/com.memoria.photos.gallery W/System.err:     at com.memoria.photos.gallery.activities.MediaActivity$onCreateOptionsMenu$2$3.invoke(MediaActivity.kt:47)
2018-12-17 09:41:27.016 7993-7993/com.memoria.photos.gallery W/System.err:     at ca.allanwang.kau.searchview.SearchView$revealOpen$1.invoke(SearchView.kt:425)
2018-12-17 09:41:27.016 7993-7993/com.memoria.photos.gallery W/System.err:     at ca.allanwang.kau.searchview.SearchView$revealOpen$1.invoke(SearchView.kt:45)
2018-12-17 09:41:27.016 7993-7993/com.memoria.photos.gallery W/System.err:     at org.jetbrains.anko.AsyncKt.runOnUiThread(Async.kt:34)
2018-12-17 09:41:27.016 7993-7993/com.memoria.photos.gallery W/System.err:     at ca.allanwang.kau.searchview.SearchView.revealOpen(SearchView.kt:418)
2018-12-17 09:41:27.016 7993-7993/com.memoria.photos.gallery W/System.err:     at ca.allanwang.kau.searchview.SearchView$bind$2.onMenuItemClick(SearchView.kt:349)
2018-12-17 09:41:27.016 7993-7993/com.memoria.photos.gallery W/System.err:     at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
2018-12-17 09:41:27.017 7993-7993/com.memoria.photos.gallery W/System.err:     at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
2018-12-17 09:41:27.017 7993-7993/com.memoria.photos.gallery W/System.err:     at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
2018-12-17 09:41:27.017 7993-7993/com.memoria.photos.gallery W/System.err:     at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
2018-12-17 09:41:27.017 7993-7993/com.memoria.photos.gallery W/System.err:     at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
2018-12-17 09:41:27.017 7993-7993/com.memoria.photos.gallery W/System.err:     at android.view.View.performClick(View.java:6597)
2018-12-17 09:41:27.017 7993-7993/com.memoria.photos.gallery W/System.err:     at android.view.View.performClickInternal(View.java:6574)
2018-12-17 09:41:27.017 7993-7993/com.memoria.photos.gallery W/System.err:     at android.view.View.access$3100(View.java:778)
2018-12-17 09:41:27.017 7993-7993/com.memoria.photos.gallery W/System.err:     at android.view.View$PerformClick.run(View.java:25885)
2018-12-17 09:41:27.018 7993-7993/com.memoria.photos.gallery W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2018-12-17 09:41:27.018 7993-7993/com.memoria.photos.gallery W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2018-12-17 09:41:27.018 7993-7993/com.memoria.photos.gallery W/System.err:     at android.os.Looper.loop(Looper.java:193)
2018-12-17 09:41:27.018 7993-7993/com.memoria.photos.gallery W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
2018-12-17 09:41:27.018 7993-7993/com.memoria.photos.gallery W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-12-17 09:41:27.018 7993-7993/com.memoria.photos.gallery W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2018-12-17 09:41:27.018 7993-7993/com.memoria.photos.gallery W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

when attempting to tint cursor

`openListener = {
                mSearchOpen = true
                it.menuY = resources.getStatusBarHeight() + this@MediaActivity.dpToPx(5)
                val editText = it.findViewById<EditText>(R.id.kau_search_edit_text)
                editText.setHintTextColor(config.searchHintText)
                editText.tintCursor(getColorCompat(R.color.search_cursor))
            }`

**Comment by AllanWang** [comment]
Is this a crash or just a stack trace? What appcompat (or androidx) version are you using? This method uses reflection which is why it is not entirely stable, but exceptions should also be caught. I will fix this once I update KAU to androidx during the winter break

**Comment by AllanWang** [comment]
Your log was probably just a printed stacktrace. Regardless, usage of reflection has been removed as it was never reliable. Cursors are no longer tinted
